title:              Blockchain Gang
email:              jkoncura@gmail.com
description:        An engineer's world
author:             Josip Končurat
baseurl:            ""
url:                "https://blockchaingang.blog/"

# Social Profiles
twitter_username:   
github_username:    josipkoncurat
facebook_username:  
linkedin_username:  jkoncurat
youtube_path:       UC466Zn2k9WmcbTLEUe896Cw

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag 
